/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;

import javax.imageio.ImageIO;

import javafx.animation.AnimationTimer;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.image.Image;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.scene.paint.Paint;
import javafx.stage.Stage;
import javafx.util.Pair;

public class App extends Application {

    public final static double WIDTH = 800.0;
    public final static double HEIGHT = 600.0;

    private int[][] tabuleiro = new int[8][8];

    private String[] nomesPecas = { "tb", "hb", "bb", "qb", "kb", "pb",
                                    "tw", "hw", "bw", "qw", "kw", "pw" };
    private Map<String, Image> imagePecas = new HashMap<>();

    private Pair<Integer, Integer> origem = null;
    private Pair<Integer, Integer> destino = null;

    private String[][] pecas = {
        {"tb", "hb", "bb", "qb", "kb", "bb", "hb", "tb"},
        {"pb", "pb", "pb", "pb", "pb", "pb", "pb", "pb"},
        {"", "", "", "", "", "", "", ""},
        {"", "", "", "", "", "", "", ""},
        {"", "", "", "", "", "", "", ""},
        {"", "", "", "", "", "", "", ""},
        {"pw", "pw", "pw", "pw", "pw", "pw", "pw", "pw"},
        {"tw", "hw", "bw", "qw", "kw", "bw", "hw", "tw"}
    };

    public App() {
        for (int l = 0; l < 8; l++) {
            for (int c = 0; c < 8; c++) { 
                tabuleiro[l][c] = (l + c) % 2;
            }
        }

        for (String nomePeca : nomesPecas) { 
            try { 
                InputStream imgIo = getClass().getResourceAsStream("/images/" + nomePeca + ".PNG");
                imagePecas.put(nomePeca, new Image(imgIo));
            } catch( Exception e ) { 
                System.out.println("Erro ao ler a imagem: " + nomePeca);
                e.printStackTrace();
            }
        }
    }

    public void start(Stage stage) { 
        Pane painel = new Pane();
        Canvas canvas = new Canvas(WIDTH, HEIGHT);
        painel.getChildren().add( canvas );
        Scene scn = new Scene( painel, WIDTH, HEIGHT);

        GraphicsContext ctx = canvas.getGraphicsContext2D();
        
        double w = WIDTH / 8.0;
        double h = HEIGHT / 8.0;

        canvas.setOnMouseClicked( e -> {
            int col = (int)(e.getX() / w);
            int lin = (int)(e.getY() / h);
            System.out.printf("Pos(%5.2f, %5.2f)  [%d, %d]\n", e.getX(), e.getY(), lin, col);           

            if (origem != null) { 
                int linOrigem = origem.getKey();
                int colOrigem = origem.getValue();
                int linDestino = lin;
                int colDestino = col;

                int desVertical = Math.abs(linOrigem - linDestino);
                int desHorizontal = Math.abs(colOrigem - colDestino);

                boolean aprovado = false;
                String pc = pecas[linOrigem][colOrigem];
                if (("pb".equals(pc) || "pw".equals(pc))) {
                    aprovado = (desVertical == 1 && desHorizontal == 0 );
                } else if (("hb".equals(pc) || "hw".equals(pc))) {
                    aprovado = ((desVertical == 1 && desHorizontal == 2 ) ||
                    (desVertical == 2 && desHorizontal == 1 )) ;
                } else if (("qb".equals(pc) || "qw".equals(pc))) {
                    aprovado = ((desVertical == desHorizontal) ||
                    desVertical == 0 || desHorizontal == 0) ;
                } else if (("kb".equals(pc) || "kw".equals(pc))) {
                    aprovado = ( (desVertical == 1 && desHorizontal == 0) ||
                    (desVertical == 0 && desHorizontal == 1) ||
                    (desVertical == 1 && desHorizontal == 1));
                } else if (("tb".equals(pc) || "tw".equals(pc))) {
                    aprovado = (desVertical == 0 || desHorizontal == 0);
                } else if (("bb".equals(pc) || "bw".equals(pc))) {
                    aprovado = (desVertical == desHorizontal);
                }

                if (aprovado){
                    pecas[linOrigem][colOrigem] = "";
                    pecas[lin][col] = pc;
                    origem = null;
                }
            }

            if (e.getButton().ordinal() == 1 && 
                !pecas[lin][col].isEmpty()) {
                origem = new Pair<>(lin, col);
            }

            if (e.getButton().ordinal() == 2) { 
                origem = null;
            }

        });

        AnimationTimer animation = new AnimationTimer() { 
            public void handle( long milisecs ) { 
                ctx.setFill(Color.WHITE);
                ctx.fillRect(0, 0, WIDTH, HEIGHT);
                for (int l = 0; l < 8; l++) {
                    for (int c = 0; c < 8; c++) { 
                        int valor = tabuleiro[l][c];
                        double x = c * w;
                        double y = l * h;
                        if (valor == 1) { 
                            ctx.setFill( Color.LIGHTGRAY );
                            ctx.fillRect(x, y, w, h);    
                        } else {
                            ctx.setStroke( Color.LIGHTGRAY );
                            ctx.strokeRect(x, y, w, h);
                        }

                        if (!pecas[l][c].isEmpty()) { 
                            String nomePeca = pecas[l][c];
                            Image img = imagePecas.get( nomePeca );
                            if (img != null) { 
                                ctx.drawImage(img, x, y, w, h);
                            }
                        }
                    }
                }

                if (origem != null) {
                    double x = origem.getValue() * w;
                    double y = origem.getKey() * h;
                    ctx.setStroke( Color.RED );
                    ctx.strokeRect(
                        x, y, w, h
                    );
                }
            }
        };

        animation.start();                

        // ctx.setStroke( Color.BLUE );
        // ctx.setLineWidth(10.0);
        // ctx.setFill( Color.RED );
        // ctx.fillRect(300, 225, 200, 150);

        stage.setScene(scn);
        stage.show();
    }


    public String getGreeting() {
        return "Jogo de Damas";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Application.launch(App.class, args);
    }
}
