spring:
  application:
    name: estoque
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/estoque_zl?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: minha-senha-favorita-123456-minha-senha-favorita-123456-minha-senha-favorita-123456
  expiration: 3600000

