POST http://localhost:8080/api HTTP/1.1
Authorization: Basic dXNlcjoxMWI3MDY5Yy0yYzVlLTQ4NGQtOWU2My02NTcwN2QyY2FhYzk=
Content-Type: application/json

{
  "nome": "Jose Santos",
  "telefone": "9",
  "email": "j@a.c"
}


###

GET http://localhost:8080/api HTTP/1.1
Authorization: Basic dXNlcjoxMWI3MDY5Yy0yYzVlLTQ4NGQtOWU2My02NTcwN2QyY2FhYzk=

###

GET http://localhost:8080/api/Jose HTTP/1.1
Authorization: Basic dXNlcjoxMWI3MDY5Yy0yYzVlLTQ4NGQtOWU2My02NTcwN2QyY2FhYzk=
