/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import javafx.application.Application;
import javafx.event.EventHandler;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;


class AssinanteEvento implements EventHandler<MouseEvent> { 
    public void handle(MouseEvent e) { 
        // System.out.println("Mouse pressionado");   
        String txt = 
            String.format(
                "Type: %s\tSource: %s\tTarget: %s\tPos(%3.1f, %3.1f)\tButton: %d",
                e.getEventType().getName(), e.getSource().getClass().getName(),
                e.getTarget().getClass().getName(), e.getX(), e.getY(), 
                e.getButton().ordinal()
            );
        System.out.println(txt);
    }
}

public class App extends Application {

    @Override
    public void start(Stage stage) { 
        BorderPane painel = new BorderPane();

        Label lblTitulo = new Label("Titulo");
        lblTitulo.setStyle("-fx-font-size: 32");
        Button btnOk = new Button("Ok");

        painel.setTop( lblTitulo );
        painel.setBottom( btnOk );

        BorderPane.setAlignment(lblTitulo, Pos.CENTER);
        BorderPane.setAlignment(btnOk, Pos.CENTER);

        Scene scn = new Scene(painel, 600, 400);

        AssinanteEvento as1 = new AssinanteEvento();
        scn.addEventFilter(MouseEvent.ANY, as1);

        stage.setScene(scn);
        stage.show();
    }

    public static void main(String[] args) {
        Application.launch(App.class, args);
    }
}
