/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import javafx.application.Application;
import javafx.event.EventHandler;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;



// class AssinanteSubTituloClique implements EventHandler<MouseEvent> { 
//     public void handle(MouseEvent e) { 
//         System.out.println("Clicado no SubTitulo");
//     }
// }


public class AppTesteEventosSetOnClicked extends Application {

    private Label lblTitulo;
    private Label lblSubTitulo;

    // class AssinanteClique implements EventHandler<MouseEvent> { 
    //     public void handle(MouseEvent e) { 
    //         if (e.getSource() == lblTitulo) {
    //             System.out.println("Clicado no Titulo");
    //         } else if (e.getSource() == lblSubTitulo) {
    //             System.out.println("Clicado no SubTitulo");
    //         }    
    //     }
    // }

    @Override
    public void start(Stage stage) { 
        BorderPane painel = new BorderPane();

        lblTitulo = new Label("Titulo");
        lblTitulo.setStyle("-fx-font-size: 32");
        

        // lblTitulo.addEventHandler(MouseEvent.MOUSE_CLICKED, 
        //     e -> System.out.println("Clicado no Titulo")
        // );
        lblTitulo.setOnMouseClicked(e -> System.out.println("Clicado no Titulo"));

        lblSubTitulo = new Label("Sub Titulo");
        lblSubTitulo.setStyle("-fx-font-size: 28");
        // lblSubTitulo.addEventHandler(MouseEvent.MOUSE_CLICKED, 
        //     e -> System.out.println("Clicado no SubTitulo")
        // );
        lblSubTitulo.setOnMouseClicked(e -> System.out.println("Clicado no SubTitulo"));

        Button btnSalvar = new Button("Salvar");
        btnSalvar.setOnMouseClicked( e -> System.out.println("Salvando ... "));
        Button btnPesquisar = new Button("Pesquisar");
        btnPesquisar.setOnMouseClicked( e -> System.out.println("Pesquisando ... "));
        VBox titulos  = new VBox(lblTitulo, lblSubTitulo);
        titulos.setAlignment(Pos.CENTER);
        painel.setTop( titulos );

        HBox botoes = new HBox(30.0, btnSalvar, btnPesquisar);
        botoes.setAlignment(Pos.CENTER);
        painel.setBottom( botoes );

        BorderPane.setAlignment(titulos, Pos.CENTER);
        BorderPane.setAlignment(botoes, Pos.CENTER);

        Scene scn = new Scene(painel, 600, 400);

        stage.setScene(scn);
        stage.show();
    }

    public static void main(String[] args) {
        Application.launch(App.class, args);
    }
}
