/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

public class AppTesteObserver {
    public static void main(String[] args) {
        Jornal globo = new Jornal("O Globo");
        Jornal estadao = new Jornal("Estadao");

        Leitor ponde = new Leitor("Luiz Ponde");
        Leitor andre = new Leitor("Andre Shaulders");
        Leitor chaui = new Leitor("Marilena Chaui");
        Leitor maria = new Leitor("Maria Carolina de Jesus");
        Leitor karnal = new Leitor("Leandro Karnal");
        Leitor conceicao = new Leitor("Conceicao Evaristo");

        estadao.adicionar(ponde);
        estadao.adicionar(chaui);
        estadao.adicionar(karnal);

        globo.adicionar(ponde);
        globo.adicionar(maria);
        globo.adicionar(conceicao);
        globo.adicionar(andre);

        estadao.publicar("Fim da guerra ou fim do mundo ?");
        globo.publicar("BBB 26 vai para reta final...");
    }
}
