/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import javafx.application.Application;

public class App {
    public String getGreeting() {
        return "Pet Shop Varias Telas";
    }

    public static void main(String[] args) {
        new App().getGreeting();
        Application.launch(PrincipalBoundary.class, args);
    }
}
