/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

public class App {

    public static void main(String[] args) {
        FolhaPagamento fp = new FolhaPagamentoEspecial();
        Funcionario f1 = new Funcionario( "Maria Silva" );
        Funcionario f2 = new Funcionario( "Jose Santos" );

        fp.fazerPagamento(f1, 3500.00);
        fp.fazerPagamento(f2, 5400.00);
    }
}
