/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

public class Contato {

    private class Interna { 
        private int valorInterno = 10;
    }

    public class Endereco { 

    }

    private int valor = 0;

    private void metodoSecreto() {
        Interna it = new Interna();
        System.out.println(it.valorInterno);
    }

    public String getGreeting() {
        metodoSecreto();
        return "Hello World!";
    }

    public static void main(String[] args) {
        Contato c1 = new Contato();
        Contato.Endereco end1 = new Contato.Endereco();
        System.out.println(new App().getGreeting());
    }
}
