/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        System.out.println("Executando Pet Shop");
        Application.launch(PetBoundary.class, args);
    }
}
