/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

public class App {

    public static void main(String[] args) {

        Jornal folha = new Jornal("Folha de Sao Paulo");
        Jornal estadao = new Jornal("Estado de Sao Paulo");

        Leitor maria = new Leitor("Maria Silva");
        Leitor lucas = new Leitor("Lucas Abreu");
        Leitor marcos = new Leitor("Marcos Santos");
        Leitor emily = new Leitor("Emily Blun");
        Leitor gustavo = new Leitor("Gustavo Saraiva");
        Leitor ana = new Leitor("Ana Guilhermina");

        folha.adicionar( emily );
        folha.adicionar( lucas );
        folha.adicionar( gustavo );

        estadao.adicionar(ana);
        estadao.adicionar(emily);
        estadao.adicionar(marcos);
        estadao.adicionar(maria);

        folha.publicar("Pane nos aeroportos, o dia vira um caos em Sao Paulo");
        folha.publicar( "Acidente no metro 15 pessoas são gravemente feridas pela porta automatica");

        estadao.publicar("Salario minimo esta muito alto segundo, Arminio Fraga");
        estadao.publicar("Fim da escala 6x1 promete acabar com a industria do pais");


    }
}
